services:
  - type: web
    name: "Ferdous Form"
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn quran_center.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ferdousdata
          property: connectionString

databases:
  - name: ferdousdata